name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Install Python dependencies
      run: |
        pip install poetry
        poetry install --no-dev
    
    - name: Build application
      run: npm run build
    
    - name: Run tests (if any)
      run: npm test --if-present
    
    - name: Deploy to Vercel (or your platform)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Ready for deployment"
        # Add your deployment commands here
        # e.g., vercel deploy --prod --token $VERCEL_TOKEN
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}